# Generated by Django 3.0.3 on 2020-07-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200716_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteName',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
