# Generated by Django 3.0.3 on 2020-07-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='name_rec',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='first_app.WebPage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='name',
            field=models.CharField(default=2, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='topic_ref',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='first_app.Topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
